### ISSUE TITLE
MUD? Just an idea...

### ISSUE THREAD

**Issue by nstrydom2** [cpp-gamedev/pkmn#10]
If you made it a MUD, then I would totally play this game. Just a thought. Keep an eye out for my email, I was taking my time to type it up. Take care.

**Comment by hentai-chan** [comment]
Thanks for the suggestion, but this feature request is a little beyond my capabilities right now. PKMN was always meant to be a simple console game, however I'll keep this idea in mind for future projects that actually use a game engine and all that jazz x)
